library(circlize)
library(webshot)

Skills <- c("Critical Race Theory",
            "Quantiative Sociology",
            "Qualitative Sociology",
            "Symbolic Interactionism",
            "Gender Womens and Sexuality Studies",
            "Professional Writing",
            "Public Speaking",
            "Improvisation",
            "Social Organization",
            "R",
            "R Studio",
            "SPSS",
            "SAS",
            "Python",
            "R Shiny",
            "Latex",
            "NVivo",
            "STATA",
            "Tableau",
            "Probability",
            "Statistics",
            "Web Scraping",
            "Data Cleaning",
            "Social Justice",
            "Feminism",
            "Analysis",
            "Regression",
            "Data Science",
            "Meta Analysis",
            "Bayesian",
            "Descriptive Stats",
            "Inferential Stats",
            "Exploratory Stats")

sds <- c("Social",
         "Data",
         "Social",
         "Social",
         "Social",
         "Social",
         "Social",
         "Social",
         "Social",
         "Data",
         "Science",
         "Data",
         "Data",
         "Science",
         "Science",
         "Science",
         "Data",
         "Data",
         "Data",
         "Science",
         "Science",
         "Data",
         "Data",
         "Social",
         "Social",
         "Science",
         "Data",
         "Science",
         "Data",
         "Science",
         "Data",
         "Science",
         "Data")

Strength <- c(7,
              8, 
              7, 
              9, 
              5, 
              9, 
              10, 
              9, 
              7, 
              10, 
              10, 
              8, 
              6, 
              4, 
              8, 
              8, 
              7, 
              6, 
              7, 
              8, 
              10,
              7, 
              10,
              8, 
              8, 
              9, 
              10,
              8, 
              9, 
              10,
              10,
              10,
              10)

df <- data.frame(Category = sds,  
                 Skills = Skills,
                 Strength = Strength,
                 stringsAsFactors = FALSE)
grid.col = c(Social = "darkmagenta",
             Data = "dodgerblue",
             Science = "green3",
             "Critical Race Theory" = "grey",
             "Quantiative Sociology" = "grey",
             "Qualitative Sociology" = "grey",
             "Symbolic Interactionism" = "grey",
             "Gender Womens and Sexuality Studies" = "grey",
             "Professional Writing" = "grey",
             "Public Speaking" = "grey",
             "Improvisation" = "grey",
             "Social Organization" = "grey",
             "R" = "grey",
             "R Studio" = "grey",
             "SPSS" = "grey",
             "SAS" = "grey",
             "Python" = "grey",
             "R Shiny" = "grey",
             "Latex" = "grey",
             "NVivo" = "grey",
             "STATA" = "grey",
             "Tableau" = "grey",
             "Probability" = "grey",
             "Statistics" = "grey",
             "Web Scraping" = "grey",
             "Data Cleaning" = "grey",
             "Social Justice" = "grey",
             "Feminism" = "grey",
             "Analysis" = "grey",
             "Regression" = "grey",
             "Data Science" = "grey",
             "Meta Analysis" = "grey",
             "Bayesian" = "grey",
             "Descriptive Stats" = "grey",
             "Inferential Stats" = "grey",
             "Exploratory Stats" = "grey")
circos.par(start.degree = 180)
ResumeChord <- chordDiagram(df, grid.col = grid.col, annotationTrack = c("grid"),
             preAllocateTracks = list(track.height = max(strwidth(unlist(dimnames(df)))))) + 
  circos.track(track.index = 1, panel.fun = function(x, y) {
  circos.text(CELL_META$xcenter, CELL_META$ylim[1], CELL_META$sector.index, 
              facing = "clockwise", niceFacing = TRUE, adj = c(0, 0.5))
}, bg.border = NA) 
circos.clear()
View(data.frame(Skill = Skills, SDS = sds))
